### PR TITLE
body 1

### PR DESCRIPTION
**Pull request by haelahpx**
give the data to the card

### CODE REVIEW

**Comment by ussoppqq** [comment]
give the photo and data

**Comment by Adomancer** [comment]
i dont have any photo

**Comment by haelahpx** [comment]
> i dont have any photo

i already give u all of the photo

**Review by haelahpx — COMMENTED** [review]
change the photo

**Comment by Adomancer** [comment]
> change the photo

no it perfect
handsome and beautifull

**Comment by ussoppqq** [comment]
> > change the photo
> 
> no it perfect handsome and beautifull

change my photo bro

**Pull request merged**
